# frozen_string_literal: true

FactoryBot.define do
  factory :consumer do
    description { 'MyString' }
    tos_accepted_at { '2021-07-14 12:16:18' }
    tos_version { 1 }
    organization { 'MyString' }

    trait :with_autogenerated do
      after(:create) do |consumer, _|
        consumer.api_environments << ApiEnvironment.first
        consumer.api_environments << ApiEnvironment.second
      end
    end

    trait :with_sandbox_ids do
      before(:create) do |consumer, _|
        consumer.sandbox_gateway_ref = '65a46870-a16a-4ded-85f1-e9fc33b03270'
        consumer.sandbox_oauth_ref = '4n-0kt4-1d-f0r-us'
      end
    end
  end
end
