# frozen_string_literal: true

FactoryBot.define do
  factory :consumer do
    description { 'MyString' }
    tos_accepted_at { '2021-07-14 12:16:18' }
    tos_version { 1 }
    organization { 'MyString' }

    trait :with_autogenerated do
      after(:create) do |consumer, _|
        consumer.api_environments << ApiEnvironment.first
        consumer.api_environments << ApiEnvironment.second
      end
    end

    trait :with_sandbox_ids do
      before(:create) do |consumer, _|
        create(:consumer_auth_ref, key: 'sandbox_gateway_ref',
                                   value: '65a46870-a16a-4ded-85f1-e9fc33b03270',
                                   consumer: consumer)
        create(:consumer_auth_ref, key: 'sandbox_acg_oauth_ref',
                                   value: '4n-0kt4-1d-f0r-us',
                                   consumer: consumer)
        create(:consumer_auth_ref, key: 'sandbox_ccg_oauth_ref',
                                   value: '4n-0kt4-1d-f0r-us-ccg',
                                   consumer: consumer)
      end
    end

    trait :with_production_apis do
      after(:create) do |consumer, _|
        api = create(:api)
        environment = Environment.find_or_create_by(name: 'production')
        consumer.api_environments << ApiEnvironment.find_or_create_by(api: api, environment: environment)
      end
    end
  end
end
