apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: lighthouse-platform-backend
  annotations:
    github.com/project-slug: department-of-veterans-affairs/lighthouse-platform-backend
    backstage.io/techdocs-ref: dir:.
  title: Lighthouse Platform Backend
  tags:
    - lighthouse
    - internal
spec:
  type: openapi
  lifecycle: production
  owner: lighthouse-okapi
  system: vets-api
  definition:
    $text: https://api.va.gov/internal/platform-backend/v0/openapi.json
