version: "3.8"

services:
  db:
    ports:
      - "5432:5432"

  kong:
    ports:
      - 4001:8001
      - 4000:8000

  prod-kong:
    ports:
      - 4003:8001
      - 4002:8000

  elasticsearch:
    ports:
      - 9200:9200
      - 9300:9300

  dynamodb:
    ports:
      - "4500:8000"
