ARG VERSION
FROM ghcr.io/department-of-veterans-affairs/health-apis-docker-octopus/developer-utils:latest

WORKDIR /etc/build

RUN retry curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose && \
    chmod +x /usr/local/bin/docker-compose