version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: ci
    depends_on:
      - db
      - kong
      - kong-migrations
      - kong-database
      - dynamodb
      - elasticsearch
    ports:
      - "8080:8080"
    environment:
      - DATABASE_HOST=${DATABASE_HOST:-db}
      - DATABASE_USER=${DATABASE_USER:-postgres}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD:-postgres}
      - RAILS_SERVE_STATIC_FILES=true
  db:
    image: postgres:13.1
    expose:
      - "5432"
    ports:
      - "5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
