version: "3.8"
services:
  app:
    build:
      context: .
      target: ci
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    ports:
      - "3000:3000"
    depends_on:
      - db
    networks:
      - backend
    environment:
      - DB_HOST=db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  db:
    image: postgres:13.1
    expose:
      - "5432"
    ports:
      - "5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - DB_HOST=db
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - backend
networks:
  backend:
    driver: bridge
volumes:
  db-data:
