version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: ci
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 8080 -b '0.0.0.0'"
    depends_on:
      - db
      - kong
      - prod-kong
      - kong-migrations
      - prod-kong-migrations
      - kong-database
      - prod-kong-database
      - dynamodb
      - elasticsearch
    environment:
      - DATABASE_HOST=${DATABASE_HOST:-db}
      - DATABASE_USER=${DATABASE_USER:-postgres}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD:-postgres}
      - RAILS_SERVE_STATIC_FILES=true
      - RAILS_ENV=development
      - DEEPLINK_SALT=badSalt123
