name: Create Maintenance Request

# set to published releases from libertybot
# on:
#   release:
#     types: [published]
on:
  push:

env:
  release_tag: ${{ github.event.release.tag_name }}

jobs:
  create-maintenance-request:
    name: Create Request
    runs-on: ubuntu-latest
    steps:
      - name: Build Request
        id: starting-release-build
        run: echo 'Generating MR...'

      - name: Display Release Tag
        id: display-release-tag
        run: echo 'release tag - ${{ env.release_tag }}'

      - name: Display Commits
        id: display-commits
        run: |
          echo 'commit - ${{ github.event.commits[0].message }}'
          echo 'commit - ${{ github.event.commits[1].message }}'

      # - name: Display commit messages
      #   id: display-commit-messages
      #   run: |
      #     for commit in ${{ env.commits }}; do
      #       if [ ${{ commit.author.name }} != 'libertybot' ]; do
      #         echo 'Messages - ${{ commit.message }}'
      #       fi
      #     done
