name: Detect Snapshot

# ? switch to only master ?
# or should we use on 'release'
# we would have access to the tag using release
# we would also not have to check head_commit.message
on: push

env:
  commit_message: ${{ github.event.head_commit.message }}
  snapshot_commit: 'Test Snapshot'

jobs:
  verify-version-update:
    name: Confirm Snapshot
    runs-on: ubuntu-latest
    steps:
      - name: MR Deployment Initialized
        if: ${{ startsWith(env.commit_message, env.snapshot_commit) }}
        run: echo  Detected ${{ env.snapshot_commit }} - beginning MR creation
      - name: MR Deployment Abandoned
        if: ${{ !startsWith(env.commit_message, env.snapshot_commit) }}
        run: |
          echo  Failed to locate MR initializer. Exiting...
          exit 1;