name: Snapshot Update

# switch to only master for merge
on: push

env:
  commit_message: ${{ github.event.head_commit.message }}
  snapshot_commit: 'Test Snapshot'

jobs:
  validate-snapshot-commit:
    name: Check Snapshot
    runs-on: ubuntu-latest
    steps:
      - name: Snapshot Commit Found
        if: startsWith(env.commit_message, env.snapshot_commit)
        run: |
          echo "${{ env.snapshot_commit }} detected - deploying"
          echo 'Preparing to run Maintenance Request Creation...'

      - name: Snapshot Commit Failed
        if: ${{ !startsWith(env.commit_message, env.snapshot_commit) }}
        run: |
          echo 'Invalid commit message - exiting'
          exit 1;
