name: Version Update

# switch to only master for merge
on: push

env:
  commit_message: ${{ github.event.head_commit.message }}

jobs:
  verify-version-update:
    name: Check Snapshot
    runs-on: ubuntu-latest
    steps:
      - name: Snapshot Commit Message
        id: commit-message
        run: |
          echo ${{ github.event.head_commit.message }}
          echo ${{ env.commit_message }}

      - name: Deploy MR
        if: startsWith(env.commit_message, 'Test Snap')
        run: echo 'Test snapshot - deploying'