name: Version Update

on: push

jobs:
  verify-version-update:
    name: Validate Version Change
    runs-on: ubuntu-latest  # windows-latest | macos-latest
    steps:
      - uses: actions/checkout@v3

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v23.1

      - name: Version Changed
        id: version-changed
        if: contains(steps.changed-files.outputs.modified_files, 'VERSION')
        run: echo 'Version Changed'

      - name: Version Did Not Change
        id: version-did-not-change
        if: contains(steps.changed-files.outputs.modified_files, '.env.sample')
        run: echo 'Version Did Not Change'
