name: Version Update

# switch to only master for merge
on: push

env:
  commit_message: ${{ github.event.head_commit.message }}
  snapshot_commit: 'Test Snapshot'

jobs:
  verify-version-update:
    name: Check Snapshot
    runs-on: ubuntu-latest
    steps:
      - name: Determine MR Deployment
        if: startsWith(env.commit_message, env.snapshot_commit)
        run: echo 'Test snapshot - deploying'